name: Hourly Hello World CRON

on:
  workflow_dispatch:
  schedule:
    - cron: "10 2 * * *"


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: |
        echo "Hello World! It's $(date)"
