name: Hourly Hello World

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: |
        echo "Hello World! It's $(date)"
